const places= [
    {
        id: '1',
        name: 'Muséé du Louvre',
        location: 'Paris',
        image: '../assets/louvre.jpeg',
        hour: '09h00 - 18h00',
        details: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium optio eaque rerum',
    },
    {
        id: '2',
        name: 'Tour Eiffel',
        location: 'Paris',
        image: '../assets/eiffel.jpeg',
        hour: '09h30 - 22h45',
        details: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium optio eaque rerum',
    },
    {
        id: '3',
        name: 'Bustronome',
        location: 'Paris',
        image: '../assets/bustronome.jpeg',
        hour: 'Départ tous les jours à 12h15',
        details: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium optio eaque rerum',
    },
    {
        id: '4',
        name: 'Tour Montparnasse',
        location: 'Paris',
        image: '../assets/montparnasse.jpg',
        hour: '11h00 - 23h30',
        details: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium optio eaque rerum',
    },
    {
        id: '5',
        name: 'Panthéon',
        location: 'Paris',
        image: '../assets/pantheon.jpeg',
        hour: '10h00 - 18h00',
        details: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium optio eaque rerum',
    },
    {
        id: '6',
        name: 'Moulin Rouge',
        location: 'Paris',
        image: '../assets/moulinRouge.jpeg',
        hour: 'A partir de 18h45',
        details: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium optio eaque rerum',
    },
    {
        id: '7',
        name: "Jardin d'Acclimatation",
        location: 'Paris',
        image: '../assets/jardinAcclim.jpeg',
        hour: '10h00 - 19h00',
        details: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium optio eaque rerum',
    },
]

export default places;